(()=>{
'use strict';

const KEY_NS=String.fromCharCode(119,97,115,101,115,104,105,98,117);
const API_DEFAULT=`https://${KEY_NS}-progress-api.fyam8.workers.dev`;
const APP_ID='vocab';
const STORAGE_KEY=KEY_NS+'_vocab_state';
const SYNC_DB=KEY_NS+'-progress-sync';
const SYNC_DB_VERSION=7;
const MAX_BATCH=10;
const RECONCILE_INTERVAL_MS=60_000;
const CONTROL_REFRESH_INTERVAL_MS=5*60_000;
const REQUEST_TIMEOUT_MS=15_000;
const te=new TextEncoder();
let running=false,lastControlRefreshAt=0,timer=null;

function apiBase(){
  const override=window[`__${KEY_NS.toUpperCase()}_PROGRESS_API__`];
  return String(override||API_DEFAULT).replace(/\/+$/,'');
}
function canonicalize(v){if(Array.isArray(v))return v.map(canonicalize);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonicalize(v[k])]));return v;}
const canonicalJson=v=>JSON.stringify(canonicalize(v));
async function sha256Hex(v){const d=await crypto.subtle.digest('SHA-256',te.encode(String(v)));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function randomToken(bytes=32){const a=new Uint8Array(bytes);crypto.getRandomValues(a);let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
async function fetchWithTimeout(url,options={}){const c=new AbortController(),id=setTimeout(()=>c.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...options,signal:c.signal});}finally{clearTimeout(id);}}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(SYNC_DB,SYNC_DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('control'))db.createObjectStore('control',{keyPath:'key'});if(!db.objectStoreNames.contains('outbox'))db.createObjectStore('outbox',{keyPath:'eventId'});if(!db.objectStoreNames.contains('deadletter'))db.createObjectStore('deadletter',{keyPath:'eventId'});if(!db.objectStoreNames.contains('seen_v2'))db.createObjectStore('seen_v2',{keyPath:'sourceKey'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('progress sync database blocked'));});}
function txDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});}
function requestValue(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function getControl(key){const db=await openDb();try{const tx=db.transaction('control','readonly'),row=await requestValue(tx.objectStore('control').get(key));await txDone(tx);return row?.value;}finally{db.close();}}
async function setControl(key,value){const db=await openDb();try{const tx=db.transaction('control','readwrite'),store=tx.objectStore('control');value==null?store.delete(key):store.put({key,value});await txDone(tx);}finally{db.close();}}
function sourceKey(id){return `${APP_ID}:${id}`;}
function deviceMetadata(){const ua=String(navigator.userAgent||'');return{deviceType:/iPad|Tablet/i.test(ua)?'tablet':/Mobi|Android|iPhone/i.test(ua)?'mobile':'desktop',osFamily:/iPhone|iPad|iOS/i.test(ua)?'iOS/iPadOS':/Android/i.test(ua)?'Android':/Windows/i.test(ua)?'Windows':/Mac OS|Macintosh/i.test(ua)?'macOS':/Linux/i.test(ua)?'Linux':'unknown',browserFamily:/Edg\//i.test(ua)?'Edge':/CriOS|Chrome\//i.test(ua)?'Chrome':/FxiOS|Firefox\//i.test(ua)?'Firefox':/Safari\//i.test(ua)?'Safari':'unknown'};}
async function getOrCreateRegistrationSeed(){const db=await openDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('control','readwrite'),store=tx.objectStore('control');let result={};const regReq=store.get('registration');regReq.onsuccess=()=>{const registration=regReq.result?.value;if(registration?.credential){result={registration};return;}const pendingReq=store.get('pendingRegistration');pendingReq.onsuccess=()=>{let pending=pendingReq.result?.value;if(!pending?.registrationId||!pending?.credential){pending={registrationId:crypto.randomUUID(),credential:randomToken(),createdAt:new Date().toISOString()};store.put({key:'pendingRegistration',value:pending});}result={pending};};pendingReq.onerror=()=>{try{tx.abort();}catch{}reject(pendingReq.error);};};regReq.onerror=()=>{try{tx.abort();}catch{}reject(regReq.error);};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('registration transaction aborted'));});}finally{db.close();}}
async function ensureRegistration(){if(!apiBase()||await getControl('syncRevoked'))return null;const seed=await getOrCreateRegistrationSeed();if(seed.registration?.credential)return seed.registration;const pending=seed.pending;if(!pending?.registrationId||!pending?.credential)return null;try{const r=await fetchWithTimeout(`${apiBase()}/v1/register-anonymous`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({registrationId:pending.registrationId,credentialHash:await sha256Hex(pending.credential),device:deviceMetadata()})});const d=await r.json().catch(()=>({}));if(!r.ok)return null;const reg={registrationId:pending.registrationId,credential:pending.credential,status:d.status||'unclassified',deviceCode:d.deviceCode||null,enrolledAt:new Date().toISOString()};await setControl('registration',reg);return reg;}catch{return null;}}
async function refreshControl(reg,force=false){if(!reg?.credential)return false;const now=Date.now();if(!force&&now-lastControlRefreshAt<CONTROL_REFRESH_INTERVAL_MS)return true;try{const r=await fetchWithTimeout(`${apiBase()}/v1/control`,{headers:{authorization:`Bearer ${reg.credential}`}}),d=await r.json().catch(()=>({}));if(r.status===401){await setControl('syncRevoked',true);lastControlRefreshAt=now;return false;}if(!r.ok)return false;const next={...reg,status:d.status||reg.status,deviceCode:d.deviceCode||reg.deviceCode};Object.assign(reg,next);await setControl('collectionDisabled',d.collectionEnabled===false);await setControl('registration',next);lastControlRefreshAt=now;return true;}catch{return false;}}

function loadState(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return x&&typeof x==='object'?x:null;}catch{return null;}}
function validIso(v){return typeof v==='string'&&Number.isFinite(Date.parse(v))&&Date.parse(v)>0?v:null;}
function localStudyDate(now=new Date()){const y=now.getFullYear(),m=String(now.getMonth()+1).padStart(2,'0'),d=String(now.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;}
function safeId(v,max=120){return String(v||'unknown').replace(/[^A-Za-z0-9._:-]/g,'_').slice(0,max)||'unknown';}
function wordRows(s){return Object.entries(s?.words&&typeof s.words==='object'?s.words:{}).map(([id,row])=>({id,...(row&&typeof row==='object'?row:{})}));}
function attempted(row){return Math.max(0,Number(row?.correct)||0)+Math.max(0,Number(row?.incorrect)||0);}
function lastLearningAt(s){const xs=wordRows(s).map(x=>validIso(x.lastStudied)).filter(Boolean).sort();return xs.at(-1)||null;}
function counts(s){const rows=wordRows(s),attemptedRows=rows.filter(x=>attempted(x)>0),mastered=attemptedRows.filter(x=>Number(x.mastery)>=4),stable=attemptedRows.filter(x=>Number(x.mastery)>=2),correct=rows.reduce((n,x)=>n+Math.max(0,Number(x.correct)||0),0),incorrect=rows.reduce((n,x)=>n+Math.max(0,Number(x.incorrect)||0),0);return{rows,attemptedRows,mastered,stable,correct,incorrect,totalAnswers:correct+incorrect};}
function buildOccurrenceRecords(s){if(!s)return[];const records=[];for(const row of wordRows(s)){const at=validIso(row.lastStudied);if(!at||attempted(row)<=0)continue;records.push({sourceRecordId:`word:${safeId(row.id,100)}`,eventType:'vocab_word_state',occurredAt:at,payload:{kind:`mastery-${Math.max(0,Math.min(4,Number(row.mastery)||0))}`,completed:Number(row.mastery)>=4,lastLearningAt:at}});}return records;}
function occurrenceSignature(s){return canonicalJson(wordRows(s).filter(x=>attempted(x)>0).map(x=>[x.id,x.correct,x.incorrect,x.mastery,x.lastStudied,x.nextReview]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))));}
function buildStateRecords(s=loadState()){if(!s)return[];const now=new Date().toISOString(),c=counts(s),last=lastLearningAt(s),today=localStudyDate();const todayCount=s?.stats?.todayKey===today?Math.max(0,Number(s?.stats?.todayCount)||0):0;const sessionSize=Math.max(1,Number(s?.settings?.sessionSize)||20);const due=c.attemptedRows.filter(x=>validIso(x.nextReview)&&Date.parse(x.nextReview)<=Date.now()).length;const mode=String(s?.settings?.mode||'recommended').slice(0,40);return[{sourceRecordId:'state:summary',eventType:'progress_state',occurredAt:now,payload:{total:c.totalAnswers,correct:c.correct,kind:`vocab-${mode}`,completed:false,...(last?{lastLearningAt:last}:{})}},{sourceRecordId:'state:mastery',eventType:'mastery_state',occurredAt:now,payload:{total:c.attemptedRows.length,correct:c.mastered.length,kind:`stable-${c.stable.length}`,completed:c.attemptedRows.length>0&&c.mastered.length===c.attemptedRows.length}},{sourceRecordId:'state:retention',eventType:'retention_state',occurredAt:now,payload:{total:c.attemptedRows.length,correct:Math.max(0,c.attemptedRows.length-due),kind:`due-${due}`,completed:c.attemptedRows.length>0&&due===0}},{sourceRecordId:'state:today',eventType:'daily_state',occurredAt:now,payload:{total:sessionSize,correct:Math.min(sessionSize,todayCount),kind:'vocab-daily-session',completed:todayCount>=sessionSize}}];}
async function queueRecord(record){const fingerprint=await sha256Hex(canonicalJson({eventType:record.eventType,payload:record.payload})),sourceHash=await sha256Hex(record.sourceRecordId),db=await openDb();try{const tx=db.transaction(['outbox','seen_v2'],'readwrite'),seen=tx.objectStore('seen_v2'),key=sourceKey(record.sourceRecordId),current=await requestValue(seen.get(key));if(current?.fingerprint===fingerprint){await txDone(tx);return false;}const revision=Math.max(0,Number(current?.revision||0))+1;const item={eventId:`${APP_ID}:${sourceHash}:r${revision}`,appId:APP_ID,sourceRecordId:record.sourceRecordId,revision,eventType:record.eventType,occurredAt:record.occurredAt,payload:record.payload,queuedAt:new Date().toISOString()};tx.objectStore('outbox').put(item);seen.put({sourceKey:key,appId:APP_ID,sourceRecordId:record.sourceRecordId,state:'queued',revision,fingerprint,at:new Date().toISOString()});await txDone(tx);return true;}finally{db.close();}}
async function queueOccurrencesIfChanged(s,reg){if(!s||reg?.status!=='production')return;const signature=await sha256Hex(occurrenceSignature(s)),key=`${APP_ID}:occurrenceSignature:${reg.registrationId}`;if(await getControl(key)===signature)return;for(const record of buildOccurrenceRecords(s))await queueRecord(record);await setControl(key,signature);}
async function uploadBaseline(reg){const key=`${APP_ID}:baselineSent:${reg.registrationId}`;if(await getControl(key))return true;const s=loadState();if(!s)return true;const c=counts(s),payload={baseline:true,eventCount:c.totalAnswers,scoredEventCount:c.totalAnswers,scoreTotal:c.correct,eventsByYear:{},capturedAt:new Date().toISOString(),progressLabel:'vocab mastery',completedCount:c.mastered.length,totalCount:c.attemptedRows.length};try{const r=await fetchWithTimeout(`${apiBase()}/v1/progress/snapshot`,{method:'PUT',headers:{'content-type':'application/json',authorization:`Bearer ${reg.credential}`},body:JSON.stringify({appId:APP_ID,generation:1,payload})}),d=await r.json().catch(()=>({}));if(r.status===401){await setControl('syncRevoked',true);return false;}if(r.status===403&&d?.code==='collection_disabled'){await setControl('collectionDisabled',true);return false;}if(!r.ok)return false;await setControl(key,{at:new Date().toISOString()});return true;}catch{return false;}}
async function readOutbox(){const db=await openDb();try{const tx=db.transaction('outbox','readonly'),rows=await requestValue(tx.objectStore('outbox').getAll());await txDone(tx);return(rows||[]).filter(x=>x?.appId===APP_ID).sort((a,b)=>String(a.queuedAt).localeCompare(String(b.queuedAt))).slice(0,MAX_BATCH);}finally{db.close();}}
async function removeOutbox(ids){if(!ids.length)return;const db=await openDb();try{const tx=db.transaction('outbox','readwrite'),store=tx.objectStore('outbox');for(const id of ids)store.delete(id);await txDone(tx);}finally{db.close();}}
async function deadletter(rows,reason){if(!rows.length)return;const db=await openDb();try{const tx=db.transaction(['outbox','deadletter'],'readwrite'),out=tx.objectStore('outbox'),dead=tx.objectStore('deadletter');for(const row of rows){dead.put({...row,deadletterAt:new Date().toISOString(),reason});out.delete(row.eventId);}await txDone(tx);}finally{db.close();}}
async function flushAvailable(reg){for(let guard=0;guard<20;guard++){const rows=await readOutbox();if(!rows.length)return true;let r,d;try{r=await fetchWithTimeout(`${apiBase()}/v1/events/batch`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${reg.credential}`},body:JSON.stringify({events:rows})});d=await r.json().catch(()=>({}));}catch{return false;}if(r.status===401){await setControl('syncRevoked',true);return false;}if(r.status===403&&d?.code==='collection_disabled'){await setControl('collectionDisabled',true);return false;}if(r.status===429||r.status>=500)return false;if(!r.ok){await deadletter(rows,`http_${r.status}:${String(d?.code||'error')}`);continue;}const rejected=new Map((Array.isArray(d?.rejected)?d.rejected:[]).map(x=>[String(x.eventId),String(x.code||'rejected')]));const retryCodes=new Set(['rate_limited','retry_later','temporarily_unavailable']);const remove=[],fatal=[];for(const row of rows){const reason=rejected.get(row.eventId);if(!reason)remove.push(row.eventId);else if(!retryCodes.has(reason))fatal.push(row);}if(remove.length)await removeOutbox(remove);if(fatal.length)await deadletter(fatal,'server_rejected');if(remove.length===0&&fatal.length===0)return false;}return false;}
async function reconcile({forceControl=false}={}){if(running)return;running=true;try{const s=loadState();if(!s)return;const reg=await ensureRegistration();if(!reg)return;if(!await refreshControl(reg,forceControl))return;if(await getControl('syncRevoked')||await getControl('collectionDisabled'))return;await uploadBaseline(reg);if(await getControl('syncRevoked')||await getControl('collectionDisabled'))return;await queueOccurrencesIfChanged(s,reg);for(const record of buildStateRecords(s))await queueRecord(record);await flushAvailable(reg);}catch{/* studying remains local-first: sync failures never block or modify learning state */}finally{running=false;}}
function start(){reconcile({forceControl:true});timer=setInterval(()=>reconcile(),RECONCILE_INTERVAL_MS);window.addEventListener('online',()=>reconcile({forceControl:true}));window.addEventListener('pagehide',()=>{reconcile();});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')reconcile();});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
window.VocabProgressCloudSync={reconcile,buildStateRecords,buildOccurrenceRecords};
})();