const fs=require('fs');
const assert=require('assert');
const sync=fs.readFileSync('progress-sync.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const has=(t,m,l)=>assert.ok(t.includes(m),`missing ${l}: ${m}`);
const lacks=(t,m,l)=>assert.ok(!t.includes(m),`forbidden ${l}: ${m}`);
const oldPersistence='const SCHEMA_VERSION=7;\nconst STORAGE_KEY="waseshibu_vocab_state";';
const adapterPersistence='const WASEDA_APP_CONFIG=Object.freeze({schemaVersion:7,storageKey:"waseshibu_vocab_state"});\nconst SCHEMA_VERSION=WASEDA_APP_CONFIG.schemaVersion;\nconst STORAGE_KEY=WASEDA_APP_CONFIG.storageKey;';

has(sync,"APP_ID='vocab'",'vocab app id');
has(sync,'String.fromCharCode(119,97,115,101,115,104,105,98,117)','shared namespace');
has(sync,"STORAGE_KEY=KEY_NS+'_vocab_state'",'stable vocab storage key');
has(sync,"SYNC_DB=KEY_NS+'-progress-sync'",'shared sync DB');
has(sync,'SYNC_DB_VERSION=7','shared sync DB version');
for(const p of ['/v1/register-anonymous','/v1/control','/v1/progress/snapshot','/v1/events/batch'])has(sync,p,p);
for(const s of ['state:summary','state:mastery','state:retention','state:today'])has(sync,s,s);
has(sync,"reg?.status!=='production'",'production-only occurrence guard');
has(sync,'canonicalJson({eventType:record.eventType,payload:record.payload})','timestamp-independent fingerprint');
has(sync,'pagehide','page-exit reconcile');
has(sync,'studying remains local-first','local-first isolation');
has(sync,"mastered=attemptedRows.filter",'objective-only mastered count');
has(sync,"stable=attemptedRows.filter",'objective-only stable count');
has(sync,"const due=c.attemptedRows.filter",'objective-only retention denominator');
has(sync,"lastLearningAt:at",'occurrence timestamp payload');
lacks(sync,'payload:{kind:`mastery-${Math.max(0,Math.min(4,Number(row.mastery)||0))}`,total:', 'no cumulative attempt count in occurrence payload');
lacks(sync,'recentResults:', 'raw recent results upload');
lacks(sync,'JSON.stringify(s)', 'raw state upload');
lacks(sync,'localStorage.setItem(', 'cloud writes local learning state');
lacks(sync,'localStorage.removeItem(', 'cloud deletes local learning state');
lacks(sync,'localStorage.clear(', 'cloud clears local learning state');
assert.ok(index.includes(oldPersistence)||index.includes(adapterPersistence),'Waseda persistence contract constants changed');
lacks(index,'localStorage.clear(', 'index clearing storage');
lacks(index,'localStorage.removeItem(STORAGE_KEY)', 'index deleting learning history');
console.log('Vocabulary cloud progress guards: CLEAN');
